server:
  port: 8762

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iceflower/spring-cloud-config-server-repo-sample.git #public Repository를 사용하는 경우
          search-paths: config-*


# actuator 기본 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
