spring:
  main:
    web-application-type: reactive
  config:
    import: "optional:configserver:http://localhost:8762/"
  cloud:
    config:
      enabled: true
      name: ${spring.application.name}
      profile: local

server:
  port: 8763
